---
- name: "Testing"
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: "Debug test"
      condition: event.payload is defined
      action:
        debug:
          msg: "{{ event.payload }}"
