---
- name: "Testing"
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: "Debug test"
      condition: true == true
      action:
        run_job_template:
          name: "testing"
          organization: "ACME Corp"
