---
- name: "Testing"
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: "Debug test"
      condition: True
      action:
        debug:
          var: ansible_eda.event
